config/routes.rb
Rails.application.routes.draw do
  get 'bookmark/new'
  get 'bookmark/create'
  # get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/lists", to: "lists#index", as: :lists

  get 'lists/new', to: 'lists#new', as: :new_list

  post 'lists', to: 'lists#create'

  get '/lists/:id', to: 'lists#show', as: :list


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmark_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new
    @bookmark = Bookmark.save!
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to lists_path
    else
      redirect_to new_list_path, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmark#create</h1>
<p>Find me in app/views/bookmark/create.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmark#new</h1>
<p>Find me in app/views/bookmark/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">

  <h1>My Movie Lists</h1>
    <ul>
      <% @lists.each do |list|  %>
      <li> <%= list.name %>
        <%= link_to "see list", list_path(list) %>
      </li>
      <% end %>
    </ul>

  <%= link_to "Create a list", new_list_path %>



</div>

app/views/lists/new.html.erb
<h1> This is a movie list form </h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit  "Submit", class: "btn btn-primary" %>
<% end %>

<%= link_to 'See all Lists', lists_path %>

app/views/lists/show.html.erb
<h1> <%= @list.name %> </h1>

<%= link_to "See all lists", lists_path %>